stages:
  - build

build:
  stage: build
  only:
    - 'master'
    - 'tags'
  image: golang:1.11.5
  script:
    - cd cmd/beach
    - export APP_VERSION=$(git describe --always --long --dirty)
    - GOOS=darwin GOARCH=amd64 go build -ldflags="-X gitlab.com/flownative/localbeach/pkg/version.Version=${APP_VERSION}" -o beach
  artifacts:
    paths:
      - cmd/beach/beach
    expire_in: '1 month'
