stages:
  - build

build:
  stage: build
  only:
    - 'master'
    - 'tags'
  image: golang:1.11.5
  script:
    - export APP_VERSION=$(git describe --always --long --dirty)
    - GOOS=darwin GOARCH=amd64 go build -ldflags="-X version.version=${APP_VERSION}" -o beach.darwin
  artifacts:
    paths:
      - beach.darwin
    expire_in: '1 day'
